USE TRAPER_KURSOVAYA

CREATE TABLE User_account
(
	PK_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(30),
	SURNAME VARCHAR(30),
	PATRONYMIC VARCHAR(30),
	LOGIN VARCHAR(30),
	PASSWORD VARCHAR(30)
)

CREATE TABLE Transport_card
(
	PK_ID_card INT PRIMARY KEY IDENTITY,
	FK_ID_owner INT REFERENCES User_account(PK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	Balance FLOAT,
	Data_issue DATE
)

CREATE TABLE Transport_vehicle
(
	PK_ID INT PRIMARY KEY IDENTITY,
	Brand VARCHAR(30),
	Model VARCHAR(30)
)

CREATE TABLE Park
(
	PK_ID INT PRIMARY KEY IDENTITY,
	Name VARCHAR(30)
)

CREATE TABLE Brigade
(
	PK_ID INT PRIMARY KEY IDENTITY,
	Name VARCHAR(30),
	Size INT,
	FK_ID_park INT REFERENCES Park(PK_ID) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Driver
(
	PK_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(30),
	SURNAME VARCHAR(30),
	PATRONYMIC VARCHAR(30),
	FK_brigade INT REFERENCES Brigade(PK_ID) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Transport
(
	PK_ID INT PRIMARY KEY IDENTITY,
	FK_ID_vehicle INT REFERENCES Transport_vehicle(PK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FK_driver_ID INT REFERENCES Driver(PK_ID) ON DELETE CASCADE ON UPDATE CASCADE
)